[libraries]
# kotlin-рефлексия (нужна spring-у)
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }
# kotlin-корутины
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
# минимальный стартер для spring boot приложения
# + bean-validation, добавляет возможность навешивать условия на поля/параметры в бинах
spring-boot-starter-validation = { group = "org.springframework.boot", name = "spring-boot-starter-validation", version.ref = "spring-boot" }
# телеграм-бот стартер для спринга через long pooling
telegrambots-springboot-longpolling-starter = { group = "org.telegram", name = "telegrambots-springboot-longpolling-starter", version.ref = "telegrambots" }
# клиент телеграма, чтобы делать запросы к api
telegrambots-client = { group = "org.telegram", name = "telegrambots-client", version.ref = "telegrambots" }

[bundles]

[plugins]
# компиляция в jvm
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
# automatically opens classes and methods (unlike in Java, the default qualifier is final in Kotlin)
# annotated or meta-annotated with Spring annotations.
kotlin-plugin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
# добавляет задачи по работе со spring boot app
spring-framework-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }

[versions]
kotlin = "2.2.21"
kotlinx-coroutines = "1.10.2"
spring-boot = "4.0.0"
telegrambots = "9.2.0"